import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';
import {existsSync,mkdirSync,readFileSync,unlinkSync} from 'node:fs';
import {homedir} from 'node:os';
const cached=`${homedir()}/Library/Caches/ms-playwright/chromium-1181/chrome-mac/Chromium.app/Contents/MacOS/Chromium`;
const executablePath=process.env.PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH||(existsSync(cached)?cached:undefined);
const browser=await chromium.launch({executablePath,headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
mkdirSync('artifacts',{recursive:true});
const boardState=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('peel-game')));
async function clickCell(x,y){const p=await page.evaluate(({x,y})=>{const r=document.querySelector('#board').getBoundingClientRect(),m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:r.left+m.e+(x*48+22)*m.a,y:r.top+m.f+(y*48+22)*m.d};},{x,y});await page.mouse.click(p.x,p.y);}
try{
 await page.goto('http://localhost:5173');
 await page.waitForFunction(()=>document.querySelector('#check').classList.contains('enabled')&&document.querySelectorAll('#plane .tile[data-id]').length===21);
 await page.locator('#finder-open').click();await page.locator('#find-input').fill('st');
 assert.equal(await page.locator('.find-match').count(),5,'finder highlights every tile touched by matching n-grams');
 assert.equal(await page.locator('.find-current').count(),2,'finder distinguishes the current occurrence');
 assert.equal(await page.locator('#find-count').innerText(),'1 / 3');await page.keyboard.press('Enter');
 assert.equal(await page.locator('#find-count').innerText(),'2 / 3','Enter advances through board matches');
 await page.locator('#find-input').fill('s');assert.equal(await page.locator('.find-match').count(),2,'single-letter finder highlights letters independent of words');
 await page.locator('#find-close').click();assert.equal(await page.locator('.find-match').count(),0,'closing finder clears its highlights');assert.equal(await page.locator('#find-bar').isHidden(),true,'closing finder removes the search row');
 await page.keyboard.press(process.platform==='darwin'?'Meta+f':'Control+f');assert.equal(await page.locator('#find-input').evaluate(element=>element===document.activeElement),true,'standard find shortcut opens the board finder');await page.keyboard.press('Escape');
 await page.locator('#finder-open').click();await page.locator('#find-input').fill('st');await page.locator('#finder-open').focus();await page.keyboard.press('Escape');
 assert.equal(await page.locator('#find-bar').isHidden(),true,'Escape closes Find even when its input is not focused');assert.equal(await page.locator('.find-match').count(),0);
 await page.waitForTimeout(120);
 await page.keyboard.press('f');assert.equal(await page.locator('#find-input').evaluate(el=>el===document.activeElement),true,'plain F opens and focuses Find');await page.keyboard.press('Escape');await page.waitForTimeout(120);
 const initialView=await page.evaluate(()=>{const m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:m.e,y:m.f};});
 await page.keyboard.press('ArrowLeft');
 const arrowView=await page.evaluate(()=>{const m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:m.e,y:m.f};});
 assert.ok(arrowView.x>initialView.x,'an arrow pans when no tile is selected');
 await page.keyboard.press('d');
 const restoredView=await page.evaluate(()=>{const m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:m.e,y:m.f};});
 assert.ok(Math.abs(restoredView.x-initialView.x)<1,'WASD pans in the opposite direction');
 await page.keyboard.press('w');await page.keyboard.press('s');
 const wasdView=await page.evaluate(()=>{const m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:m.e,y:m.f};});
 assert.ok(Math.abs(wasdView.y-initialView.y)<1,'vertical WASD panning is reversible');
 await page.screenshot({path:'artifacts/screenshot-desktop.png',fullPage:true});
 const originalState=await boardState(),original=originalState.board;
 await page.locator('[data-tool="select"]').click();
 const firstTile=await page.locator('#plane [data-id="t0"]').boundingBox(),lastTile=await page.locator('#plane [data-id="t4"]').boundingBox();
 await page.mouse.move(firstTile.x+2,firstTile.y+2);await page.mouse.down();await page.mouse.move(lastTile.x+lastTile.width-2,lastTile.y+8,{steps:5});await page.mouse.up();
 assert.equal(await page.locator('#plane .selected').count(),5);assert.equal(await page.locator('[data-tool="move"]').getAttribute('class'),'tool active');
 const groupScale=await page.evaluate(()=>new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform).a);
 await page.mouse.move(firstTile.x+20,firstTile.y+20);await page.mouse.down();await page.mouse.move(firstTile.x+20,firstTile.y+20-48*groupScale,{steps:5});await page.mouse.up();
 assert.ok((await boardState()).board.filter(t=>['t0','t1','t2','t3','t4'].includes(t.id)).every(t=>t.y===-1),'fresh marquee group drags immediately without a menu click');
 await page.keyboard.press('z');assert.deepEqual((await boardState()).board,original);
 await page.locator('#free-tiles').click();assert.equal(await page.locator('#free-tiles').getAttribute('aria-pressed'),'true');
 const freeIds=await page.locator('#plane .free-tile').evaluateAll(tiles=>tiles.map(t=>t.dataset.id));assert.ok(freeIds.length>0);
 const candidate=freeIds[0];await page.locator(`#plane [data-id="${candidate}"]`).click();await page.keyboard.press('Delete');
 assert.equal(await page.locator(`#plane [data-id="${candidate}"]`).count(),0);assert.equal(await page.locator('#plane .bad').count(),0);assert.match(await page.locator('#status').innerText(),/All words connect/);
 await page.locator('#undo').click();assert.deepEqual((await boardState()).board,original);await page.locator('#free-tiles').click();assert.equal(await page.locator('#plane .free-tile').count(),0);
 await page.locator('#board-share').click();const portable=await page.locator('#position-code').inputValue();assert.ok(portable.startsWith('PEEL1.'));
 await page.locator('#local-share-now').click();await page.waitForFunction(()=>document.querySelector('#local-sharing-status').textContent.startsWith('Shared locally'));
 const sharingId=await page.evaluate(()=>localStorage.getItem('peel-client-id')),sharedFile=`artifacts/live-boards/${sharingId}.json`;
 assert.deepEqual(JSON.parse(readFileSync(sharedFile,'utf8')).state,originalState);unlinkSync(sharedFile);
 await page.screenshot({path:'artifacts/screenshot-export.png',fullPage:true});
 const downloaded=page.waitForEvent('download');await page.locator('#position-download').click();const download=await downloaded;await download.saveAs('artifacts/exported-board.json');
 const artifactDownload=page.waitForEvent('download');await page.locator('#position-artifact').click();await (await artifactDownload).saveAs('artifacts/test-board-and-metrics.html');
 const offline=await browser.newContext({offline:true}),artifactPage=await offline.newPage();const artifactErrors=[];artifactPage.on('pageerror',e=>artifactErrors.push(e.message));
 await artifactPage.goto(new URL('./artifacts/test-board-and-metrics.html',import.meta.url).href);
 assert.deepEqual(await artifactPage.evaluate(()=>JSON.parse(document.querySelector('#snapshot').textContent).state),originalState);
 await artifactPage.locator('[data-inspect="coverage"]').hover();assert.equal(await artifactPage.locator('[data-overlay="coverage"]').getAttribute('class'),'overlay active');
 await artifactPage.locator('[data-inspect="hull"]').click();await artifactPage.locator('h1').hover();assert.equal(await artifactPage.locator('[data-overlay="hull"]').getAttribute('class'),'overlay active');
 assert.deepEqual(artifactErrors,[]);await offline.close();
 await page.locator('#position-code').fill('bad code');await page.locator('#position-import').click();assert.match(await page.locator('#position-message').innerText(),/not a valid/);assert.deepEqual(await boardState(),originalState);
 await page.locator('#position-code').fill(portable);await page.locator('#position-import').click();assert.deepEqual(await boardState(),originalState);
 await page.locator('#board-share').click();await page.locator('#position-file').setInputFiles('artifacts/exported-board.json');await page.waitForFunction(()=>!document.querySelector('.modal'));assert.deepEqual(await boardState(),originalState);
 await page.locator('#input-demo').click();await page.locator('#input-demo').click();
 assert.equal(await page.locator('#plane .selected').innerText(),'E');
 await page.locator('#demo-next').click();assert.equal(await page.locator('.ghost-layer .ghost').count(),1);
 await page.locator('#demo-next').click();assert.ok((await boardState()).board.some(t=>t.l==='E'&&t.x===5&&t.y===-1));
 for(let i=0;i<4;i++)await page.locator('#demo-next').click();
 assert.equal((await boardState()).board.find(t=>t.x===1&&t.y===0).l,'O','tour performs the swap');
 await page.locator('#demo-next').click();await page.locator('#demo-next').click();assert.equal(await page.locator('#plane .selected').count(),5);
 await page.locator('#demo-next').click();assert.equal(await page.locator('.ghost-layer.blocked').count(),1,'tour floats the group over occupied cells');
 const cursorBox=await page.locator('.demo-pointer').boundingBox(),boardBox=await page.locator('#board').boundingBox();assert.ok(cursorBox.x>=boardBox.x&&cursorBox.x<boardBox.x+boardBox.width,'tour cursor stays on the demonstrated board cell');
 await page.screenshot({path:'artifacts/screenshot-input-tour.png',fullPage:true});
 for(let i=0;i<4;i++)await page.locator('#demo-next').click();assert.equal(await page.locator('#plane .selected').count(),5);assert.deepEqual((await boardState()).board,original);
 await page.keyboard.press('Escape');
 await page.locator('#plane .tile[data-id]').first().dblclick();
 assert.equal(await page.locator('#plane .selected').count(),5,'double-click selects a word');
 await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');
 const moved=(await boardState()).board;
 assert.equal(moved[0].x,original[0].x-1);
 await page.locator('#undo').click();assert.deepEqual((await boardState()).board,original);
 await page.locator('#redo').click();assert.deepEqual((await boardState()).board,moved);
 await page.locator('#undo').click();
 await page.locator('#plane .tile[data-id]').first().click();await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('.ghost-layer.blocked').count(),1,'keyboard floats over occupied tile');
 await page.keyboard.press('Enter');assert.deepEqual((await boardState()).board,original,'occupied cell rejects placement');
 for(let i=0;i<5;i++)await page.keyboard.press('ArrowRight');
 assert.equal(await page.locator('.ghost-layer.blocked').count(),0,'can float beyond occupied run');
 await page.keyboard.press('Enter');assert.equal((await boardState()).board[0].x,6);
 await page.locator('#undo').click();
 await page.locator('#plane .tile[data-id]').first().click();
 await page.keyboard.press('Delete');assert.equal(await page.locator('#rack .tile').count(),1);
 await page.locator('#rack .tile').click();await clickCell(0,0);
 assert.equal(await page.locator('#plane .tile[data-id]').count(),21);
 assert.equal(await page.locator('#rack .tile').count(),0);
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('All words connect'));
 // Actual pointer drag, preserving the grabbed tile and exact cell offset.
 const dragTile=page.locator('#plane [data-id="t1"]');const box=await dragTile.boundingBox();
 const scale=await page.evaluate(()=>new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform).a);
 await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+48*scale,box.y+box.height/2-48*scale,{steps:5});await page.mouse.up();
 const afterDrag=(await boardState()).board.find(t=>t.id==='t1');assert.equal(afterDrag.x,2);assert.equal(afterDrag.y,-1);
 assert.equal(await page.locator('.component-outline').count(),1,'only the smaller disconnected group is outlined while editing');
 await page.locator('#peel').click();assert.equal(await page.locator('.component-flash .component-outline').count(),2,'a blocked peel briefly highlights all disconnected groups');
 await page.waitForFunction(()=>!document.querySelector('.component-flash'));assert.equal(await page.locator('.component-outline').count(),1,'largest group returns to unoutlined after the flash');
 const outlineColors=await page.locator('.component-outline').evaluateAll(paths=>paths.map(path=>path.getAttribute('stroke')));assert.equal(new Set(outlineColors).size,outlineColors.length);
 await page.screenshot({path:'artifacts/screenshot-components.png',fullPage:true});
 await page.locator('#undo').click();
 assert.equal(await page.locator('.component-outline').count(),0,'outlines disappear when the board reconnects');
 // Selection starts inside tiles and catches an edge without including the center.
 await page.keyboard.press('Escape');await page.locator('[data-tool="select"]').click();
 const corner=await page.locator('#plane [data-id="t0"]').boundingBox();
 const beforeSelection=(await boardState()).board;
 await page.mouse.move(corner.x+1,corner.y+1);await page.mouse.down();await page.mouse.move(corner.x+9,corner.y+9,{steps:4});await page.mouse.up();
 assert.equal(await page.locator('#plane .selected').count(),1,'marquee touching tile corner selects it');
 assert.deepEqual((await boardState()).board,beforeSelection,'starting selection within a tile never drags it');
 const marqueeEvent=await page.evaluate(()=>JSON.parse(localStorage.getItem('peel-qa-journal-v1')).events.findLast(event=>event.action==='selection.marquee'));
 assert.equal(marqueeEvent.details.startedOn.id,'t0');assert.equal(marqueeEvent.selection.length,1);
 assert.ok(marqueeEvent.details.pixelRect.width>0,'QA journal keeps the exact selection rectangle');
 await page.locator('#qa-open').click();await page.locator('#qa-note').fill('The group selection did something surprising here.');await page.locator('#qa-add-note').click();
 assert.match(await page.locator('.qa-events article').first().innerText(),/qa.note/);
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('peel-qa-journal-v1')).events.at(-1).details.note),'The group selection did something surprising here.');
 await page.screenshot({path:'artifacts/screenshot-qa.png',fullPage:true});
 await page.locator('#qa-close').click();
 await page.locator('#plane [data-id="t0"]').click();assert.equal(await page.locator('#plane .selected').count(),0,'clicking selected tile deselects');
 await page.locator('[data-tool="move"]').click();
 await page.locator('#plane [data-id="t0"]').click();await page.waitForTimeout(400);await page.locator('#plane [data-id="t0"]').click();
 assert.equal(await page.locator('#plane .selected').count(),0,'move mode click-again deselects');
 // Swap is available after picking up a tile and hovering the destination.
 await page.waitForTimeout(400);await page.locator('#plane [data-id="t0"]').click();
 await page.locator('#plane [data-id="t1"]').hover();await page.keyboard.press('x');
 assert.equal(await page.locator('.swap-target').count(),1);
 assert.match(await page.locator('.placement-hint').innerText(),/swap S ↔ T/);
 await page.locator('#plane [data-id="t1"]').click();
 let swapped=(await boardState()).board;assert.equal(swapped.find(t=>t.id==='t0').x,1);assert.equal(swapped.find(t=>t.id==='t1').x,0);
 await page.locator('#undo').click();await page.keyboard.press('x');
 // Space peels directly into the hand; Alt swaps a rack letter and holds the displaced one.
 await page.keyboard.press('Space');
 assert.equal(await page.locator('#rack .selected').count(),1,'peeled letter is already in hand');
 assert.equal((await boardState()).bag.length,11);
 const afterPeel=await boardState();
 await page.keyboard.press('Escape');assert.equal(await page.locator('#rack .selected').count(),0);
 await page.keyboard.press('Space');assert.equal(await page.locator('#rack .selected').count(),1,'Space picks up the existing rack letter');
 assert.deepEqual(await boardState(),afterPeel,'picking up a rack tile does not draw or change the board');
 await page.keyboard.press('Space');assert.equal(await page.locator('#rack .selected').count(),1,'Space keeps an already-held rack letter');
 assert.deepEqual(await boardState(),afterPeel);

 await page.locator('#plane [data-id="t1"]').hover();await page.keyboard.down('Alt');
 assert.equal(await page.locator('.swap-target').count(),1);
 await page.locator('#plane [data-id="t1"]').click();await page.keyboard.up('Alt');
 assert.equal(await page.locator('#rack .selected').innerText(),'T');
 await page.locator('#undo').click();await page.locator('#rack .tile').click();
 const empty=await page.evaluate(()=>{const r=document.querySelector('#board').getBoundingClientRect(),m=new DOMMatrix(getComputedStyle(document.querySelector('#plane')).transform);return {x:r.left+m.e+262*m.a,y:r.top+m.f+22*m.a};});
 await page.mouse.move(empty.x,empty.y);assert.equal(await page.locator('.ghost-layer .ghost').count(),1);
 await page.mouse.click(empty.x,empty.y);assert.equal(await page.locator('#rack .tile').count(),0);
 assert.match(await page.locator('#status').innerText(),/All words connect/);
 // Auto-check is on by default; invalid words highlight without pressing Check.
 await page.locator('#demo-reset').click();
 const letterS=page.locator('#rack .tile').filter({hasText:/^T$/}).first();await letterS.click();await clickCell(0,0);
 const letterT=page.locator('#rack .tile').filter({hasText:/^T$/}).first();await letterT.click();await clickCell(1,0);
 await page.waitForFunction(()=>document.querySelectorAll('#plane .bad').length===2);
 assert.match(await page.locator('#status').innerText(),/Check TT/);
 await page.locator('#check').click();assert.equal(await page.locator('#plane .bad').count(),0);
 assert.equal(await page.locator('#check').getAttribute('aria-pressed'),'false');
 await page.reload();assert.equal(await page.locator('#check').getAttribute('aria-pressed'),'false');
 assert.equal(await page.locator('#plane .tile[data-id]').count(),2,'board persists across reload');
 await page.locator('#check').click();await page.waitForFunction(()=>document.querySelectorAll('#plane .bad').length===2);
 // Suggest has its own preview while automatic validation remains live.
 await page.evaluate(()=>localStorage.setItem('peel-game',JSON.stringify({board:[],rack:[...`STONE`].map((l,i)=>({id:`q${i}`,l})),bag:[{id:'q5',l:'S'}],total:6})));
 await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#rack .tile').length===5);
 await page.locator('#suggest').click();
 assert.equal(await page.locator('.suggestion-tile').count(),5);
 assert.equal(await page.locator('.suggestion-rack').count(),5);
 assert.match(await page.locator('#status').innerText(),/Idea: NOTES/);
 assert.equal(await page.locator('#suggest-label').innerText(),'Place idea');
 await page.locator('#suggest').click();
 assert.equal(await page.locator('#plane .tile[data-id]').count(),5);
 assert.equal(await page.locator('#rack .tile').count(),0);
 assert.match(await page.locator('#status').innerText(),/All words connect/);
 await page.locator('#score-open').click();assert.match(await page.locator('.modal').innerText(),/Hull fill/);assert.match(await page.locator('.score-table').innerText(),/NOTES/);assert.match(await page.locator('.score-run').innerText(),/30 modifiers/);await page.screenshot({path:'artifacts/screenshot-score.png',fullPage:true});
 await page.locator('#run-start').click();assert.equal(await page.locator('[data-run-modifier]').count(),3,'a run offers three scoring-rule choices');
 const chosenModifier=await page.locator('[data-run-modifier]').first().getAttribute('data-run-modifier');await page.locator('[data-run-modifier]').first().click();
 assert.equal(await page.locator('#rack .tile').count(),21,'optimization run starts a fresh little bunch');
 assert.match(await page.locator('#peel').innerText(),/Bank 1/,'the main peel control becomes the stage bank action');
 let runState=await page.evaluate(()=>JSON.parse(localStorage.getItem('peel-score-run-v1')));assert.equal(runState.status,'playing');assert.deepEqual(runState.modifierIds,[chosenModifier]);
 await page.evaluate(state=>localStorage.setItem('peel-game',JSON.stringify(state)),originalState);await page.reload();await page.waitForFunction(()=>document.querySelectorAll('#plane .tile[data-id]').length===21);
 await page.locator('#score-open').click();assert.match(await page.locator('.run-equation').innerText(),/BASE/);assert.equal(await page.locator('#run-bank').isEnabled(),true,'a valid empty-rack board meeting the target can be banked');await page.locator('#run-bank').click();
 runState=await page.evaluate(()=>JSON.parse(localStorage.getItem('peel-score-run-v1')));assert.equal(runState.stage,2);assert.equal(runState.status,'choosing');assert.equal(runState.scores.length,1);
 await page.locator('[data-run-modifier]').first().click();assert.equal(await page.locator('#rack .tile').count(),1,'choosing the next rule peels one letter into the hand');assert.equal((await boardState()).bag.length,11);
 assert.match(await page.locator('#peel').innerText(),/Bank 2/);
 await page.locator('#score-open').click();await page.locator('#run-abandon').click();assert.match(await page.locator('.score-run').innerText(),/Start a five-stage run/);await page.locator('.modal-close').click();
 // Dictionary overrides add missing common words and hide obscure bundled words.
 await page.locator('#dictionary-open').click();await page.locator('#dictionary-word').fill('sex');
 assert.match(await page.locator('#dictionary-state').innerText(),/not included/);await page.locator('#dictionary-action').click();
 assert.match(await page.locator('#dictionary-state').innerText(),/your addition/);
 await page.locator('#dictionary-word').fill('kae');assert.match(await page.locator('#dictionary-state').innerText(),/bundled word/);await page.locator('#dictionary-action').click();
 assert.match(await page.locator('#dictionary-state').innerText(),/hidden from bundled list/);await page.locator('.modal-close').click();
 let overrides=await page.evaluate(()=>JSON.parse(localStorage.getItem('peel-dictionary-overrides-v1')));
 assert.deepEqual(overrides,{added:['SEX'],removed:['KAE']});
 await page.evaluate(()=>localStorage.setItem('peel-game',JSON.stringify({board:[...`SEX`].map((l,x)=>({id:`u${x}`,l,x,y:0})),rack:[],bag:[],total:3})));
 await page.reload();await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('All words connect'));
 assert.equal(await page.locator('#plane .bad').count(),0,'custom word participates in Auto-check');
 await page.locator('#dictionary-open').click();await page.locator('#dictionary-word').fill('sex');await page.locator('#dictionary-action').click();await page.locator('.modal-close').click();
 await page.waitForFunction(()=>document.querySelectorAll('#plane .bad').length===3);
 await page.locator('#dictionary-open').click();await page.locator('#dictionary-word').fill('sex');await page.locator('#dictionary-action').click();await page.locator('.modal-close').click();
 await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('All words connect'));
 // A complete guided round, including every draw and placement.
 await page.locator('#demo-reset').click();
 for(let i=0;i<7;i++)await page.locator('#demo-next').click();
 assert.equal(await page.locator('#plane .tile[data-id]').count(),21);
 for(let i=0;i<12;i++){
  await page.locator('#demo-next').click();assert.equal(await page.locator('#rack .tile').count(),1);
  await page.locator('#demo-next').click();assert.equal(await page.locator('#rack .tile').count(),0);
  assert.equal(await page.locator('#plane .tile[data-id]').count(),22+i);
  assert.equal(await page.locator('#plane .bad').count(),0);
 }
 assert.equal(await page.locator('#bunch-stat').innerText(),'0');
 assert.match(await page.locator('#status').innerText(),/Bananas/);
 await page.screenshot({path:'artifacts/screenshot-demo.png',fullPage:true});
 await page.locator('#peel').click();assert.match(await page.locator('.modal h2').innerText(),/Bananas/);await page.keyboard.press('Escape');
 // Manual takeover resets the demo safely.
 await page.locator('#plane .tile[data-id]').first().click();await page.keyboard.press('ArrowLeft');await page.keyboard.press('Enter');
 assert.match(await page.locator('#demo-play').innerText(),/Watch the demo/);
 await page.locator('#demo-play').click();await page.locator('#demo-play').click();assert.ok((await boardState()).board.length<33);
 // Full bunch distribution and game rules.
 await page.locator('#new').click();await page.locator('#classic').click();
 let state=await boardState();assert.equal(state.total,144);assert.equal(state.rack.length,21);assert.equal(state.bag.length,123);
 await page.keyboard.press('Space');assert.equal(await page.locator('#rack .selected').getAttribute('data-id'),state.rack[0].id,'Space picks up the first tile from a full rack');
 assert.deepEqual(await boardState(),state);
 await page.keyboard.press('Escape');

 await page.locator('#peel').click();state=await boardState();assert.equal(state.bag.length,123,'cannot peel with rack tiles');
 await page.locator('#rack .tile').first().click();await page.locator('#dump').click();state=await boardState();assert.equal(state.rack.length,23);assert.equal(state.bag.length,121);
 await page.locator('#undo').click();state=await boardState();assert.equal(state.rack.length,21);assert.equal(state.bag.length,123);
 const boardDumpId=state.rack[0].id;
 await page.locator(`#rack [data-id="${boardDumpId}"]`).click();await clickCell(0,0);
 await page.locator(`#plane [data-id="${boardDumpId}"]`).click();await page.locator('#dump').click();state=await boardState();
 assert.equal(state.board.length,0,'Dump removes a selected board tile');assert.equal(state.rack.length,23);assert.equal(state.bag.length,121);
 await page.locator('#undo').click();state=await boardState();assert.equal(state.board.length,1);assert.equal(state.rack.length,20);assert.equal(state.bag.length,123);
 await page.setViewportSize({width:390,height:844});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'mobile has no horizontal overflow');
 await page.screenshot({path:'artifacts/screenshot-mobile.png',fullPage:true});
 // Live score remains open through board edits, and exposes the exact pond geometry.
 await page.setViewportSize({width:1440,height:1000});
 const ringPosition={board:Array.from({length:16},(_,i)=>({id:`ring${i}`,l:'A',x:i%4,y:Math.floor(i/4)})).filter(t=>t.x===0||t.x===3||t.y===0||t.y===3),rack:[],bag:[],total:12};
 await page.locator('#board-share').click();await page.locator('#position-code').fill(JSON.stringify(ringPosition));await page.locator('#position-import').click();
 const boardSizeBefore=await page.locator('#board').boundingBox(),planeBefore=await page.locator('#plane').getAttribute('style');
 await page.locator('#score-open').click();assert.equal(await page.locator('.modal-backdrop').count(),0,'score is a nonmodal side panel');
 assert.deepEqual(await page.locator('#board').boundingBox(),boardSizeBefore,'opening score preserves board dimensions');assert.equal(await page.locator('#plane').getAttribute('style'),planeBefore,'opening score preserves board zoom and pan');
 await page.reload();await page.waitForSelector('.score-panel');
 await page.locator('[data-score-inspect="hull"]').hover();assert.equal(await page.locator('.hull-outline path').count(),1);assert.equal(await page.locator('.cave-area').count(),0);assert.equal(await page.locator('#plane .shape-label').count(),0);assert.equal(await page.locator('#inspection-caption').isVisible(),true);assert.equal(await page.locator('.hull-contact[data-contact="side"]').count(),16);assert.equal(await page.locator('.hull-contact[data-contact="corner"]').count(),0);
 await page.locator('[data-score-inspect="ponds"]').hover();assert.equal(await page.locator('.pond-cell').count(),4);
 await page.locator('[data-score-inspect="coverage"]').hover();assert.equal(await page.locator('.cave-area').getAttribute('fill-rule'),'evenodd');assert.match(await page.locator('#inspection-caption').innerText(),/Caves · 0/);
 await page.screenshot({path:'artifacts/screenshot-live-ponds.png',fullPage:true});
 await page.locator('#plane [data-id="ring1"]').click();await page.keyboard.press('Delete');assert.equal(await page.locator('.score-panel').count(),1);
 await page.locator('[data-score-inspect="ponds"]').hover();assert.equal(await page.locator('.pond-cell').count(),0,'pond score and overlay update after opening its boundary');
 await page.locator('[data-score-inspect="coverage"]').hover();assert.match(await page.locator('#inspection-caption').innerText(),/Caves · 5/);assert.equal(await page.locator('.cave-area').count(),1);
 await page.locator('#plane').hover({force:true});await page.keyboard.press('z');
 await page.locator('[data-score-inspect="ponds"]').hover();assert.equal(await page.locator('.pond-cell').count(),4,'undo restores inspected pond');
 await page.locator('.score-table [data-score-inspect]').first().hover();assert.ok(await page.locator('.score-inspected').count()>0);
 await page.locator('.alternative-metrics>summary').click();await page.locator('[data-score-inspect="rectangle"]').hover();assert.equal(await page.locator('.density-rectangle').count(),1);
 await page.locator('[data-score-inspect="diamond"]').hover();assert.equal(await page.locator('.inspection-shape path').count(),1);assert.match(await page.locator('.shape-label').innerText(),/radius 3 · 24 cells/);
 await page.screenshot({path:'artifacts/screenshot-live-diamond.png',fullPage:true});
 await page.locator('[data-score-inspect="box"]').hover();assert.equal(await page.locator('.box-rectangle').count(),1);
 await page.locator('[data-score-inspect="solid"]').focus();assert.equal(await page.locator('.solid-rectangle').count(),1);
 await page.locator('[data-score-inspect="longest"]').hover();assert.ok(await page.locator('.score-inspected').count()>0);
 await page.locator('[data-score-inspect="strongest"]').hover();assert.ok(await page.locator('.score-inspected').count()>0);
 await page.locator('[data-score-inspect="woven"]').hover();assert.equal(await page.locator('.score-inspected').count(),4);
 await page.locator('#score-close').click();assert.equal(await page.locator('.score-inspected').count(),0);
 await page.reload();await page.waitForSelector('#score-open');assert.equal(await page.locator('.score-panel').count(),0,'closed score preference survives reload');
 if(existsSync('artifacts/optimization/improved.json')){
  await page.locator('#board-share').click();await page.locator('#position-file').setInputFiles('artifacts/optimization/improved.json');
  await page.waitForFunction(()=>document.querySelector('#status').textContent.includes('All words connect'));
  assert.equal(await page.locator('#plane .tile[data-id]').count(),144);
  await page.locator('#score-open').click();await page.locator('.alternative-metrics>summary').click();await page.locator('[data-score-inspect="diamond"]').hover();await page.screenshot({path:'artifacts/optimization/improved-live-score.png',fullPage:true});
  await page.locator('#score-close').click();
 }
 assert.deepEqual(errors,[],'no browser runtime errors');
 console.log('Passed: board letter/n-gram finder, five-stage scoring-run setup and modifier choice, local QA journaling and timestamped notes, custom dictionary add/hide/restore, transparent board scoring, commonness-ranked suggestions, arrow/WASD panning, board/rack dumping, edge-intersection marquee, click-again deselection, placement ghost, keyboard float over collisions, Space peel into hand, board and rack swaps, selection, collision prevention, undo/redo, rack return/placement, pointer drag, live validation and opt-out persistence, all 12 demo peels, completion, manual takeover, full-bunch rules, and mobile layout.');
}finally{await browser.close();}
