// These are editorial game preferences, not claims that lower tiers are invalid English.
export const TIER_VERSION='editorial-v1';
export const TIERS=['S','A','B','C','D','F'];
export const TIER_LABELS={S:'Exceptional',A:'Expressive',B:'Everyday',C:'Specialist / unreviewed',D:'Obscure short forms',F:'Avoid'};
const groups={
 S:'TURGID VERACITY SERENDIPITY LUMINOUS EPHEMERAL MELANCHOLY LABYRINTH ELOQUENCE RESONANCE PALIMPSEST INCANDESCENT PETRICHOR',
 A:'TWIXT COIF SUEDE VELVET AMBER AZURE WRY WISP GLOAM GLEAM GLINT BRISK BRINE BRUME FJORD QUARTZ QUIVER QUIET QUELL QUIP ZEST ZEPHYR EMBER BRIAR THORN THICKET CANOPY GOSSAMER MURMUR RIPPLE RIVULET TORRENT TUNDRA VERDANT VIBRANT WISTFUL WINSOME SULLEN SOMBER STALWART STOLID STOIC LITHE LISSOME LACONIC LIMPID LUCID LURID TAWDRY TEPID TACTILE DAPPLE DAPPLED DUSKY DUSK DAWN TWILIGHT SOLSTICE EQUINOX ELEGY SONNET STANZA LYRIC CADENCE TIMBRE TANGIBLE TENACIOUS AUDACIOUS AVARICE AUSTERE ARDENT ARCANE APLOMB ALCHEMY ANATHEMA AMBIVALENT CAPRICIOUS CATHARSIS CHIMERA CLAMOR CLARION CLEMENT COGENT CONFLUENCE DILIGENT DISSONANCE EFFERVESCENT EMPATHY ENIGMA ETHEREAL EVANESCENT EXUBERANT FERVOR FLORID FORTITUDE FRUGAL GARRULOUS HALCYON HARBINGER IDYLL IDYLLIC INEFFABLE INGENIOUS INTREPID IRIDESCENT JUBILANT JUXTAPOSE LANGUID LEVITY LOQUACIOUS MAGNANIMOUS MELLIFLUOUS METTLE MIRTH NEBULOUS NUANCE OPULENT PARADOX PENSIVE PERENNIAL PERSPICACIOUS PITHY PLACID POIGNANT PRISTINE PROWESS QUIXOTIC RADIANT RANCOR REDOLENT REVERIE RUEFUL SAGACIOUS SANGUINE SARDONIC SATURNINE SILHOUETTE SOLACE SONOROUS SUBLIME SUCCINCT SURREAL TACIT TACITURN TEMPEST TRANQUIL TREPIDATION UMBRAGE VENERABLE VEX VEXED VIGIL VISCERAL VIVACIOUS WHIMSY ZENITH',
 B:'BY BED RUN PARTY DONOR AT AN AS BE DO GO HE IF IN IS IT ME MY NO OF OH ON OR OX SO TO UP US WE YES NOT THE AND ATE EAT TEA CAT DOG LOG GOD RAT BAT HAT MAT MAN WOMAN CHILD HOUSE HOME GARDEN STONE STONES STAR START STARTS RAIN RAINS NOTE NOTES EAST WEST NORTH SOUTH YEAST YEASTS TEAR TEARS PLATE PLATES BALL BALLS LADY AREA LEAD CAR RED SEA EAR ART TEN ORE GET GAS SAG DANGER GANDER RANGED STAPLE PLEATS PASTEL PETALS QUIZ WINE FIX FUN CANE COIFED SOAP SOUP WATER FRIEND FAMILY PEOPLE MUSIC TABLE CHAIR BREAD MILK SCHOOL OFFICE SHOP WORK PLAY GAME WORD TILE LETTER BOOK READ WRITE WALK JUMP SWIM SLEEP DREAM HAPPY SAD GREEN BLUE BROWN WHITE BLACK',
 C:'QI QIS ZA ZAS XI XU JO KA KI KY MYC ZAX ADZ ADZE ADO AHA OHO OI OY YE YO',
 D:'AVO AVOS SOU SOUS AA AAS AAL AALS ABO ABOS AE AI AIS AIT AITS AKE AKES AUK AUKS EAU EAUX EME EMES EMU EMUS ERN ERNE ERNS ERNES ETA ETAS KAE KAES KAF KAFS KAS KAT KATS KEP KEPS KEX KHI KHIS KOP KOPS LEU LEUS LEI OBA OBAS OBI OBIS OCA OCAS ODA ODAS ODS OE OES OKA OKAS OMS OPE OPES ORA ORE ORES ORT ORTS OSE OSES OUD OUDS OUK OUKS OUP OUPS OUS OYE OYES PED PEDS PEH PEHS PIA PIAS PYE PYES RAI RAIS RAS REI REIS SAI SAIS SAU SKA SOK SOLI SOT SOTS TAE TAES TAI TAIS TAV TAVS TAW TAWS TEL TELS TET TETS TUI TUIS ULU ULUS UMM UMS UNS URD URDS URE URES UTA UTAS UTE UTES UTU UTUS VAE VAES VAV VAVS VAW VAWS WAE WAES WAT WATS WAW WAWS YAE YAG YAGS YOD YODS ZEA ZEAS ZEK ZEKS ZHO ZHOS',
 F:'PUL PULS EUOI EUOUAE OOR OORIE OUPA OUPAS OUPH OUPHE OUPHES OUPHS QAID QAIDS QOPH QOPHS',
};
// Familiar animal/music/material words shouldn't become casualties of a short-form list.
groups.D=groups.D.split(' ').filter(w=>!'AUK AUKS EMU EMUS ORE ORES SKA OUD OUDS'.split(' ').includes(w)).join(' ');
export const CURATED_TIERS=new Map(Object.entries(groups).flatMap(([tier,text])=>text.split(/\s+/).filter(Boolean).map(word=>[word,tier])));
export function normalizeTierPolicy(value){
 const overrides={};for(const [word,tier] of Object.entries(value?.overrides||{}))if(/^[A-Z]{2,24}$/.test(word)&&TIERS.includes(tier))overrides[word]=tier;
 return {version:TIER_VERSION,minimum:TIERS.includes(value?.minimum)?value.minimum:'F',overrides};
}
export function wordTier(word,ranks=new Map(),policy={}){
 const w=word.toUpperCase(),personal=policy.overrides?.[w],curated=CURATED_TIERS.get(w);
 if(TIERS.includes(personal))return {tier:personal,source:'Your rating',provisional:false};
 if(curated)return {tier:curated,source:'Editorial rating',provisional:false};
 if(ranks.has(w)&&ranks.get(w)<=20000)return {tier:'B',source:'Provisional · frequent in the bundled corpus',provisional:true};
 return {tier:'C',source:'Provisional · not reviewed',provisional:true};
}
export function tierAllowed(tier,minimum='F'){return TIERS.includes(tier)&&TIERS.includes(minimum)&&TIERS.indexOf(tier)<=TIERS.indexOf(minimum);}
export function filteredDictionary(base,ranks,policy,exceptions={added:[],removed:[]}){
 const hidden=new Set(exceptions.removed),out=new Set();
 for(const w of new Set([...base,...exceptions.added]))if(!hidden.has(w)&&tierAllowed(wordTier(w,ranks,policy).tier,policy.minimum))out.add(w);
 return out;
}
